apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-1password-autounseal
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-1password-autounseal
rules:
  - apiGroups: ["onepassword.com"]
    resources: ["onepassworditems"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-1password-autounseal
subjects:
  - kind: ServiceAccount
    name: vault-1password-autounseal
    namespace: vault
roleRef:
  kind: Role
  name: vault-1password-autounseal
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-1password-autounseal
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-1password-autounseal
  template:
    metadata:
      labels:
        app: vault-1password-autounseal
    spec:
      serviceAccountName: vault-1password-autounseal
      containers:
        - name: vault-1password-autounseal
          image: ghcr.io/erik142/vault-op-autounseal:0.2.0
          imagePullPolicy: Always
          args: ["-config", "/app/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          env:
            - name: ONEPASSWORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: onepassword-token
                  key: onepassword-token
      volumes:
        - name: config
          configMap:
            name: vault-1password-autounseal
