on:
  pull_request:
    branches:
      - master

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
              ghcr.io/erik142/vault-op-autounseal:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
