on:
  push:
    branches:
      - master

jobs:
  bump_version:
    if: "!contains(github.event.head_commit.message, 'chore: bump version to')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ssh-key: "${{secrets.COMMIT_KEY}}"
          fetch-tags: true
          fetch-depth: 0
      - name: Get next version number
        id: version-retriever
        run: echo "new_version=$(make version_bump)" >> "$GITHUB_ENV"
      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add examples/
          git commit -m "chore: bump version to v$new_version"
          git push origin master
          git tag -a -m "chore: bump version to v$new_version" "v$new_version"
          git push origin "v$new_version"
