on:
  push:
    branches:
      - master

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-tags: true
      - name: Get next version number
        id: version-retriever
        run: echo "new_version=$(make version_bump)" >> "$GITHUB_ENV"
      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -a -m "chore: bump version to v$new_version" "v$new_version"
          git push origin "v$new_version"
