# This workflow will build a container image and publish it to a private
# container registry.

name: Publish container image in registry

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          go-build-cache
        key: go-build-cache-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-build-cache-
    - name: inject cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v3.1.0
      with:
        cache-map: |
          {
            "go-build-cache": "/root/.cache/go-build"
          }
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
    - name: Get tag
      uses: dawidd6/action-get-tag@v1
      with:
        strip_v: true
      id: tag
    - name: Build and publish container image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            ghcr.io/erik142/vault-op-autounseal:${{ steps.tag.outputs.tag }}
            ghcr.io/erik142/vault-op-autounseal:latest
        cache-from: type=gha,scope=autounseal
        cache-to: type=gha,ignore-error=true,mode=max,scope=autounseal
